apiVersion: "v1"
kind: "Service"
metadata:
  name: "product-inventory-service-service"
  namespace: "app-poc"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: "product-inventory-service"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "product-inventory-service"
  type: "LoadBalancer"

