spring.application.name=product-inventory-service
server.port=8080

mongo.host=${MONGO_HOST:localhost}
mongo.port=${MONGO_PORT:27017}
mongo.username=${MONGO_USER:admin}
mongo.password=${MONGO_PASSWORD:admin}
mongo.database=${MONGO_DB:product_inventory}

spring.data.mongodb.uri=mongodb://${mongo.username}:${mongo.password}@${mongo.host}:${mongo.port}/${mongo.database}?authSource=admin
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.bestarch.demo=INFO